# To start creating a K8S deployment
# kubectl apply -f=deployment.yaml

apiVersion: apps/v1
kind: Deployment # kind of K8S object e.g. service, job
metadata:
  # all possible attributes e.g.
  # name, namespace, labels, annotations, generateName, ownerReferences, finalizers, clusterName, creationTimestamp, deletionGracePeriodSeconds, deletionTimestamp, generation, resourceVersion, selfLink, uid
  name: kub-second-app-deployment
  # namespace: default
  # labels:
  #   app: kub-second-app
  # annotations:
  #   description: "kub-second-app deployment"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kub-second-app
      tier: backend
  # template = pod 
  # kubectl create deployment kub-first-app --image=berlinleephoenix/kub-first-app:2
  template:
    # kind: Pod
    metadata: 
      labels:
        app: kub-second-app
        tier: backend
      annotations:
        description: "This is a Pod for kub-second-app"
    spec: 
      containers:
        - name: kub-second-app
        # equivalent to --image= in kubectl create deployment kub-first-app --image=berlinleephoenix/kub-first-app:2
          image: berlinleephoenix/kub-first-app:2
        # - name: kub-first-app
        #   image: berlinleephoenix/kub-first-app:1
        # - name: kub-second-app
        #   image: berlinleephoenix/kub-second-app:2
