# docs: https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.27/#service-v1-core
apiVersion: v1
kind: Service
metadata:
  name: kub-second-app
spec:
  selector: 
    app: kub-second-app
  ports:
    - protocol: 'TCP'
      port: 80 # outside world
      targetPort: 8080 # inside container
    # - protocol: 'TCP'
    #   port: 443
    #   targetPort: 443
  type: LoadBalancer